# Generated by Django 5.0.14 on 2026-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary of the emergency event.', max_length=150)),
                ('description', models.TextField(help_text='Detailed description of the incident circumstances.')),
                ('location', models.CharField(help_text='Physical address or geographical reference of the incident.', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', help_text='Current state in the incident lifecycle.', max_length=25)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Urgency level of the incident response.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
