# Generated by Django 5.0.14 on 2026-06-11 16:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the incident.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title summarizing the incident.', max_length=150)),
                ('description', models.TextField(help_text='Detailed description of the incident.')),
                ('category', models.CharField(choices=[('FIRE', 'Fire'), ('ACCIDENT', 'Accident'), ('MEDICAL', 'Medical'), ('CRIME', 'Crime'), ('NATURAL_DISASTER', 'Natural Disaster'), ('OTHER', 'Other')], default='OTHER', help_text='Categorization of the incident event.', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='WGS 84 latitude coordinates.', max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='WGS 84 longitude coordinates.', max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('address', models.TextField(help_text='Physical location details.')),
                ('image', models.ImageField(blank=True, help_text='Attached incident capture.', null=True, upload_to='incidents/')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', help_text='Development status of incident lifecycle.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='System-assigned urgency level.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The Operator assigned to resolve or dispatch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='The Citizen user who logged this incident.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
