# Generated by Django 5.0.14 on 2026-06-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], help_text='The status prior to this update.', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], help_text='The status resulting from this update.', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Optional comments/reasons detailing the change.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the transition occurred.')),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who performed the status transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='The incident whose status was modified.', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Incident status histories',
                'ordering': ['timestamp'],
            },
        ),
    ]
