# Generated by Django 5.0.14 on 2026-06-11 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, help_text='Optional comments/reasons detailing the assignment change.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the assignment occurred.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The Operator or Admin who assigned the incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The Operator assigned to handle the incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='The incident that was assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Incident assignment histories',
                'ordering': ['timestamp'],
            },
        ),
    ]
